services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - datejuridice_net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - datejuridice_net

  ms_case_extractor:
    build: ./ms-case-extractor
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    ports:
      - "8010:8000"
    restart: unless-stopped
    networks:
      - datejuridice_net

  ms_case_extractor_consumer:
    build: ./ms-case-extractor
    depends_on:
      - kafka
      - ms_pdftext
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    volumes:
      - ./data/txt:/data/txt:ro
    command: ["python", "consumer.py"]
    restart: unless-stopped
    networks:
      - datejuridice_net

  ms_ingestion_web:
    build: ./ms_ingestion_web
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    ports:
      - "8000:8000"
    networks:
      - datejuridice_net

  ms_dataquality:
    build: ./ms_dataquality
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    networks:
      - datejuridice_net

  ms_pdftext:
    build: ./ms_pdftext
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    volumes:
      - ./data/pdf:/data/pdf
      - ./data/txt:/data/txt
    networks:
      - datejuridice_net

  ms_storage:
    build: ./ms_storage
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    volumes:
      - ./data/enriched:/data/enriched
    restart: unless-stopped
    networks:
      - datejuridice_net

  ms_bff:
    build: ./ms_bff
    depends_on:
      - ms_ingestion_web
      - ms_case_extractor
    environment:
      CASE_EXTRACTOR_URL: http://ms_case_extractor:8000
      INGESTION_URL: http://ms_ingestion_web:8000
      TXT_DIR: /data/txt
      ENRICHED_FILE: /data/enriched/cases.json
    volumes:
      - ./data/txt:/data/txt:ro
      - ./data/pdf:/data/pdf:ro
      - ./data/enriched:/data/enriched:ro
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - datejuridice_net

  web_ui:
    build: ./web_ui
    depends_on:
      - ms_bff
    ports:
      - "8080:80"
    networks:
      - datejuridice_net

networks:
  datejuridice_net:
    driver: bridge
